# Site settings
email: stephane.guidoin[at]gmail.com
baseurl: ""
paginate: 5
paginate_path: "/page-:num"
google_analytics: 

# SEO settings
title: Dataholic 
description: Données, visualisations, technologies, lectures, politique
url: "https://dataholic.ca"
#url: "http://localhost:4000"
twitter_username: hoedic
default_img: background_principal.webp

# Profile settings
name: Stéphane Guidoin
profile_img: profil.webp
profile: "Stéphane Guidoin est un amateur de chocolat, d'aïkido, de voile et de jardinage et dont le cerveau turbine constamment sur l'impact des technologies, les crises longues et ce qui fait que la vie mérite d'être vécue."
social:
  github: https://github.com/hoedic
  linkedin: https://www.linkedin.com/in/stephaneguidoin

# Build settings
include: ["_categories", "images"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
